javascripts:
- base:
  - jquery
  - jquery-ui
  - jrails
  - application
- admin:
  - jquery
  - jquery-ui-1.7.2.custom.min.js
  - ui.multiselect.js
  - jrails
  - "markitup/jquery.markitup.pack.js"
  - "markitup/sets/markdown/set.js"
  - admin
stylesheets:
- base:
  - application
- admin:
  - default
  - admin
  - formtastic
  - formtastic_changes_admin
  - jquery-ui-1.7.2.custom.css
  - ui.multiselect.css
  - "markitup/skins/simple/style.css"
  - "markitup/sets/markdown/style.css"

